apiVersion: v1
kind: Pod
metadata:
  name: first-python
  labels:
    app: pythonapp1
spec:
  containers:
    - name: pythonapp1
      image: omkarkhare/python:Node1
      ports:
        - containerPort: 8080
