apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: python-deployment
  labels:
    app: python-app
spec:
  replicas: 2
  selector:
    matchlabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      container:
        - name: python-container
          image: omkarkhare/pystritch:21
          ports:
          - containerPort: 82
