version: '2.1'
orbs:
  aws-cli: circleci/aws-cli@3.1
jobs:
  cli-commands:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          aws-region: AWS_REGION_NAME
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
      - run:
          command: |
            aws s3 ls
workflows:
  aws-cli:
    jobs:
      - cli-commands
