version: '2.1'
orbs:
  aws-cli: circleci/aws-cli@3.1
jobs:
  configure-role-arn:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          aws-region: AWS_REGION_NAME
          aws-access-key-id: AWS_ACCESS_KEY_ID
      - run:
          command: |
            aws sts assume-role --role-arn "arn:aws:iam::064178608086:role/Ansible-test-role" --role-session-name AWSCLI-Session
workflows:
  aws-cli:
    jobs:
      - configure-role-arn
