version: 2.1
jobs:
  build:
    docker:
      - image: alpine:3.15
    steps:
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
            apk add --no-cache bash curl python3 py3-pip && pip3 install awscli
            apk add --no-cache sudo
            aws --version
            export role_arn=arn:aws:iam::064178608086:role/Ansible-test-role
            export source_profile=default
            cat ~/.aws/config
            
